# This is a GitHub Actions workflow file.
# It should be placed in the .github/workflows/ directory of your repository.
# This workflow automatically updates the newsletter archive and sitemap.

name: Build Newsletter Archive & Sitemap

on:
  push:
    branches:
      - main # This triggers the workflow on pushes to the 'main' branch
    paths:
      - 'archive/**' # Trigger on new newsletters
      - 'assets/newsletter_archive_template.html' # Trigger on template changes

  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner
    
    # Grant permissions for the action to push code back to the repository
    permissions:
        contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 # Action to get your code into the runner

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Action to set up a Node.js environment
        with:
          node-version: '20' # Specify the Node.js version

      - name: Install dependencies
        run: npm install # Assumes you have a package.json

      - name: Run the archive build script
        run: node scripts/build.js # Execute the script that updates the archive page
      
      - name: Run the sitemap generation script
        run: node scripts/generate-sitemap.js # Execute the script that creates the sitemap

      - name: Commit and push changes
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
            # Add both the updated archive and the new sitemap
            git add index.html sitemap.xml

            # Commit only if there are actual changes to the files
            git diff --staged --quiet || git commit -m "Automated: Update archive and sitemap"
            
            git push
